# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89eaf6a1d81e62d0f803384f8d84a801e5b748a9d7cc9f06995570ec26bf0614d38975689934b0636d494a64c8ba4c8f097e8c88a983f985b2908b59cbc4f4c7

test:
  secret_key_base: b2aacf528c1a30a72a13931689eef813de0a5d708861c69721a6b81d5d37ec3a6fd848cbfb9ce9c7429e5254ba35e060a8dee78bd84598ff58c54839d9409325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
